apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: trino
    repo: https://trinodb.github.io/charts/
    version: 1.42.2 
    releaseName: trino
    namespace: trino
    # File to override default values file (Optional)
    #additionalValuesFiles:
    #  - base/values.yaml

resources:
  - configuration