---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: rustfs
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - list:
        elements:
          - cluster: in-cluster
  template:
    metadata:
      name: rustfs
    spec:
      destination:
        name: "{{cluster}}"
        namespace: rustfs-system
      project: default
      source:
        path: manifests/platform-infra/rustfs
        repoURL: https://github.com/dormstd/k8s-dataplatform-poc.git
        targetRevision: HEAD
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true